### ISSUE TITLE
problems with pf2 system

### ISSUE THREAD

**Issue by SlatedFishawa** [Unarekin/FoundryVTT-Battle-Transitions#12]
When I click the ADD TO STEP button, there is no response
![QQ20241117-201928](https://github.com/user-attachments/assets/de841701-33eb-4b0b-a2c3-da40b37adf27)

**Comment by Unarekin** [comment]
Looks like a check I had to prevent the Add Step dialog from showing up when hitting the enter key was also causing the dialog to not show up when using the PF2E module.

I've implemented a more reliable method for this, and version 1.0.7 is available to install through Foundry to fix this :)

**Comment by SlatedFishawa** [comment]
Thank you very much for your update :D
