### ISSUE TITLE
Video transition is cut in bottom left corner

### ISSUE THREAD

**Issue by FrancisJose65** [Unarekin/FoundryVTT-Battle-Transitions#8]
Installment info:
- Foundry V12, build 331
- System: Fabula Ultima (ProjectFU) 2.4.0-alpha.26
- New world with only Batle Transitions and Color Picked enabled

Bug:
No matter the video or size, the video gets **"cut"** in the bottom left corner, only showing 2/3s of the video:

![video_bug](https://github.com/user-attachments/assets/abf32571-5a29-43e9-9d90-2b0963a9ef67)

Steps to reproduce:
- Create 2 scenes
- In the configuration of one of the scenes, go to the Battle Transitions and add a Video to the Transition Steps
- Load a video and leave the default options as they are
- Activate the scene with the video transition

**Comment by Unarekin** [comment]
Fixed in 1.0.5
